export const JOURNAL_PAGE_QUOTES = [
    "The unexamined life is not worth living. — Socrates",
    "You have to know what you stand for, not just what you stand against. — Laurie Halse Anderson",
    "Clarity precedes mastery. — Robin Sharma",
    "The privilege of a lifetime is to become who you truly are. — Carl Jung",
    "Your mind is your greatest asset, so be careful what you put into it. — Unknown",
    "Self-reflection is the school of wisdom. — Baltasar Gracián",
    "In solitude, the mind gains strength and learns to lean upon itself. — Laurence Sterne",
    "The soul always knows what to do to heal itself. The challenge is to silence the mind. — Caroline Myss",
    "What we think, we become. — Buddha",
    "The only journey is the one within. — Rainer Maria Rilke",
    "The quieter you become, the more you can hear. — Ram Dass",
    "You must find the place inside yourself where nothing is impossible. — Deepak Chopra",
    "The longest journey is the journey inward. — Dag Hammarskjöld",
    "Sometimes, you have to look back to see how far you've come. — Unknown",
    "The wound is the place where the Light enters you. — Rumi",
    "Awareness is the greatest agent for change. — Eckhart Tolle",
    "Until you make the unconscious conscious, it will direct your life and you will call it fate. — Carl Jung",
    "Your vision will become clear only when you can look into your own heart. — Carl Jung",
    "Peace comes from within. Do not seek it without. — Buddha",
    "The mind is everything. What you think, you become. — Buddha",
    "Radiate boundless love towards the entire world. — Buddha",
    "Nothing can harm you as much as your own thoughts unguarded. — Buddha",
    "Let go of what you think you know. — Zen Proverb",
    "You, yourself, as much as anybody in the entire universe, deserve your love and affection. — Buddha",
    "Every morning we are born again. What we do today matters most. — Buddha",
    "If you want others to be happy, practice compassion. If you want to be happy, practice compassion. — Dalai Lama",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. — Buddha",
    "True love is born from understanding. — Buddha"
];
